<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>v</string>
	</array>
	<key>foldingStartMarker</key>
	<string>^module\b|^function\b|^task\b|\bbegin\b</string>
	<key>foldingStopMarker</key>
	<string>^endmodule\b|^endfunction\b|^endtask\b|\bend\b</string>
	<key>name</key>
	<string>Verilog</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>/\*</string>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.verilog</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\*/</string>
			<key>name</key>
			<string>comment.block.verilog</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.verilog</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(//).*$\n?</string>
			<key>name</key>
			<string>comment.line.double-slash.verilog</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>^\s*`\s*(define|undef|ifdef|else|endif|include|resetall)\b</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.import.verilog</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?=(?://|/\*))|$</string>
			<key>name</key>
			<string>meta.preprocessor.verilog</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b([0-9]+'[bBoOdDhH][0-9a-fA-FxXzZ]+|[0-9]+)\b</string>
			<key>name</key>
			<string>constant.numeric.verilog</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(if|else|case|endcase|for|while|always|begin|end|function|endfunction|endmodule)\b</string>
			<key>name</key>
			<string>keyword.control.verilog</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(input|output|inout|reg|wire|parameter|assign)\b</string>
			<key>name</key>
			<string>storage.type.verilog</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(posedge|negedge)\b</string>
			<key>name</key>
			<string>keyword.operator.verilog</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.function.verilog</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.module.verilog</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.parameters.begin.verilog</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.module.verilog</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.parameters.end.verilog</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?:\b(module) (\w+)\s*(\()(.*?)(\))?)</string>
			<key>name</key>
			<string>meta.module</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.verilog</string>
	<key>uuid</key>
	<string>F4ABA507-80D1-479E-B42A-C2CB05F64145</string>
</dict>
</plist>
